environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      configuration: Debug

    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      configuration: Release

    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      configuration: Retail

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      buildcfg: debug64

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      buildcfg: release64

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      buildcfg: retail64
      
    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
      buildcfg: debug64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
      buildcfg: release64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
      buildcfg: retail64 
      
shallow_clone: true

for:
  
# ======================================
# Windows
# ======================================

  -
    matrix:
      only:
      - job_name: Windows
  
    init:
      - git clone --recursive --depth 1 https://github.com/RudjiGames/rapp_template    rapp_template
      
    install:
      - rapp_template\build\tools\bin\windows\genie.exe --file=rapp_template\src\app_template\genie\genie.lua vs2022
      
    build: 
      project: .build\windows\vs2022\rapp_template\projects\rapp_template.sln
    
# ======================================
# Linux
# ======================================

  -
    matrix:
      only:
      - job_name: Linux

    init:
      - sudo apt-get update --allow-releaseinfo-change && sudo apt install -y xorg libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libegl1-mesa-dev libx11-dev
      - git clone --recursive --depth 1 https://github.com/RudjiGames/rapp_template    rapp_template
      - git clone --depth 1 https://github.com/bkaradzic/GENie  GENie		# build GENie from source: `GLIBC_2.29' not found
      - cd GENie && make && cd ..
      - git clone --depth 1 https://github.com/glfw/glfw        glfw      
      - mkdir glfwbuild && cd glfwbuild && cmake ../glfw -DGLFW_BUILD_TESTS=OFF && make -j4 && sudo make install && cd ..     

    install:
      - ./GENie/bin/linux/genie --file=rapp_template/src/app_template/genie/genie.lua --gcc=linux-gcc gmake
  
    build_script:
      - cd ./rapp_template/.build/linux/linux-gcc/app_template/projects/
      - make config=${buildcfg}

# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
      - git clone --recursive --depth 1 https://github.com/RudjiGames/rapp_template    rapp_template
      - git clone --depth 1 https://github.com/bkaradzic/GENie GENie  # build GENie from source: we don't know the target CPU, can't use ARM binary from 'build'
      - cd GENie && make && cd ..

    install:
      - ./GENie/bin/darwin/genie --file=rapp_template/src/app_template/genie/genie.lua --gcc=osx-arm64 gmake
    
    build_script:
      - cd ./rapp_template/.build/osx/clang/app_template/projects/
      - make config=${buildcfg}
